/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.akotadakura;
import static org.junit.jupiter.api.Assertions.assertNotNull;
//import static org.junit.Assert.*;
//
//import org.junit.Test;

import org.junit.jupiter.api.Test;

public class AppTest {

//  @Test
  @Test
  void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting());
  }
}
